### PR TITLE
Skip copying documentation file when target already exists

### LINKED ISSUE #74: IOException: The file 'obj\Debug\net35\annotated\System.Core.xml' already exists.
> error MSB4018: The "AnnotatorBuildTask" task failed unexpectedly.
> System.IO.IOException: The file 'obj\Debug\net35\annotated\System.Core.xml' already exists.

```
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
at System.IO.File.Copy(String sourceFileName, String destFileName)
at TunnelVisionLabs.ReferenceAssemblyAnnotator.AnnotatorBuildTask.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

@sharwell If the file exists, would there ever be a reason that it would need to be updated? Rather than passing `overwrite: true`, maybe the IOException could be swallowed based on the error code (probably ERROR_FILE_EXISTS).

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #74. Verified that `File.Copy` throws an exception whose `(ushort)ex.HResult` is `80` due to the target being an existing file.

⚠ This may not be the right (or only) fix needed to close the issue. See issue discussion.

### CODE REVIEW

File: TunnelVisionLabs.ReferenceAssemblyAnnotator/AnnotatorBuildTask.cs [hunk 1]
```diff
@@ -104,7 +104,14 @@ public override bool Execute()
             string targetDocumentation = Path.ChangeExtension(outputAssembly, ".xml");
             if (File.Exists(sourceDocumentation))
```
Comment (sharwell) [inline TunnelVisionLabs.ReferenceAssemblyAnnotator/AnnotatorBuildTask.cs]: Why not this?

```suggestion
            if (File.Exists(sourceDocumentation) && !File.Exists(targetDocumentation))
```

Comment (jnm2) [reply TunnelVisionLabs.ReferenceAssemblyAnnotator/AnnotatorBuildTask.cs]: We can sure add that, but we can't rely on File.Exists because we might be racing with a concurrent build process.

(I generally avoid non-atomic file system operations by default. An arbitrary number of things may change on disk between when File.Exists returns and when you act on the value it returns, so its only real use is an optimization to avoid throwing and catching an exception 99% of the time.)

Comment (sharwell) [reply TunnelVisionLabs.ReferenceAssemblyAnnotator/AnnotatorBuildTask.cs]: It would be fine to have both for now. The exception handling could be removed when the machine caching strategy is implemented.

**Review by sharwell — APPROVED** [review]
