### PR TITLE
Polish from user reports

### LINKED ISSUE #28: Incorrect warning about StringComparer differing in nullability from IEqualityComparer<string?>
I'm not sure of the cause, but I'm seeing this on net472 using alpha 53 and Microsoft.NETCore.App.Ref 3.0.0:

```cs
void M(IEnumerable<string?> values)
{
    // CS8620 Argument of type 'StringComparer' cannot be used for parameter 'comparer' of type
    // 'IEqualityComparer<string?>' in 'IEnumerable<string?> Enumerable.Distinct<string?>(
    // IEnumerable<string?> source, IEqualityComparer<string?> comparer)' due to differences in
    // the nullability of reference types.
    //              ↓
    values.Distinct(StringComparer.CurrentCultureIgnoreCase);
}
```

`StringComparer` does in fact implement `IEqualityComparer<string?>`, not `IEqualityComparer<string>`. If I target `netcoreapp3.0`, the warning goes away.

### LINKED ISSUE #29: Net35 projects lose reference to System.Data when referencing ReferenceAssemblyAnnotator
@sharwell You had mentioned that the net35 reference assemblies include one mixed-mode implementation assembly, System.Data, and that Mono.Cecil fails to rewrite mixed-mode assemblies. I'm seeing this in a net35 project with an explicit (necessary) reference to System.Data:

> MSB3267 The primary reference "System.Data", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v3.5". To resolve this problem, either remove the reference "System.Data" or retarget your application to a framework version which contains "System.Data".

Along with compiler errors due to missing types from that assembly.

I wonder if https://github.com/0xd4d/dnlib can write mixed-mode assemblies. If not, I wonder if either Cecil or dnlib can strip out the mixed-mode stuff since this assembly is only being used as a ref assembly. If not, the original non-rewritten System.Data "reference" assembly should stay referenced so that the project can compile.

### PR DESCRIPTION
**Pull request by sharwell**
* Skip mixed-mode assemblies with a warning (Fixes #29)
* Ensure the rewritten assembly always has `[assembly: ReferenceAssembly]`
* Annotate implemented interfaces (Fixes #28)
* Report a build error if `AnnotatedReferenceAssemblyVersion` is not defined

### CODE REVIEW

File: TunnelVisionLabs.ReferenceAssemblyAnnotator/CustomAttributeFactory.cs [hunk 1]
```diff
@@ -76,5 +76,12 @@ public CustomAttribute AttributeUsage(AttributeTargets validOn, bool? allowMulti
 
             return customAttribute;
         }
+
+        public CustomAttribute ReferenceAssembly()
+        {
+            MethodDefinition constructor = _wellKnownTypes.SystemRuntimeCompilerServicesReferenceAssemblyAttribute.Resolve().Methods.Single(method => method.IsConstructor && !method.IsStatic && method.Parameters.Count == 0);
```
Comment (sharwell) [inline TunnelVisionLabs.ReferenceAssemblyAnnotator/CustomAttributeFactory.cs:82]: ❕ This failed in tests:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at TunnelVisionLabs.ReferenceAssemblyAnnotator.CustomAttributeFactory.ReferenceAssembly()
   at TunnelVisionLabs.ReferenceAssemblyAnnotator.Program.EnsureReferenceAssemblyAttribute(AssemblyDefinition assemblyDefinition, WellKnownTypes wellKnownTypes, CustomAttributeFactory attributeFactory)
   at TunnelVisionLabs.ReferenceAssemblyAnnotator.Program.Main(TaskLoggingHelper log, String referenceAssembly, String annotatedReferenceAssembly, String outputAssembly)
   at TunnelVisionLabs.ReferenceAssemblyAnnotator.AnnotatorBuildTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

File: TunnelVisionLabs.ReferenceAssemblyAnnotator/Program.cs [hunk 2]
```diff
@@ -93,6 +106,16 @@ private static void AnnotateType(TaskLoggingHelper? log, TypeDefinition typeDefi
             }
 
             Annotate(typeDefinition, annotatedTypeDefinition, attributesOfInterest);
+            for (var i = 0; i < typeDefinition.Interfaces.Count; i++)
+            {
+                for (int j = 0; j < annotatedTypeDefinition.Interfaces.Count; j++)
```
Comment (jnm2) [inline TunnelVisionLabs.ReferenceAssemblyAnnotator/Program.cs:111]: One is `var` and one is `int`.

File: global.json [hunk 3]
```diff
@@ -1,5 +1,5 @@
 {
   "sdk": {
-    "version": "2.1.801"
+    "version": "3.0.100"
```
Comment (jnm2) [inline global.json]: Can you add a `"rollforward"` property such as `"latestFeature"`?

File: TunnelVisionLabs.ReferenceAssemblyAnnotator/Program.cs [hunk 4]
```diff
@@ -93,6 +106,16 @@ private static void AnnotateType(TaskLoggingHelper? log, TypeDefinition typeDefi
...
+                {
+                    if (EquivalenceComparers.TypeReference.Equals(typeDefinition.Interfaces[i].InterfaceType, annotatedTypeDefinition.Interfaces[j].InterfaceType))
+                    {
+                        Annotate(typeDefinition.Interfaces[i], annotatedTypeDefinition.Interfaces[j], attributesOfInterest);
```
Comment (jnm2) [inline TunnelVisionLabs.ReferenceAssemblyAnnotator/Program.cs]: On phone so maybe I'm missing it, but are you annotating typeDefinition.BaseType?

Comment (jnm2) [reply TunnelVisionLabs.ReferenceAssemblyAnnotator/Program.cs]: Wasn't thinking. BaseType isn't a custom attribute target, so it's gotta be handled by the annotation on the type itself.

File: TunnelVisionLabs.ReferenceAssemblyAnnotator/CustomAttributeFactory.cs (hunk 1 above)
Comment (jnm2) [reply TunnelVisionLabs.ReferenceAssemblyAnnotator/CustomAttributeFactory.cs]: It's first defined in .NET Framework 4.0: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.referenceassemblyattribute?view=netframework-4.8#applies-to

According to https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md#definition-of-ref-assemblies, `ReferenceAssemblyAttribute` can be defined internally like other attributes.

Comment (jnm2) [reply TunnelVisionLabs.ReferenceAssemblyAnnotator/CustomAttributeFactory.cs:82]: It's first defined in .NET Framework 4.0: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.referenceassemblyattribute?view=netframework-4.8#applies-to

According to https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md#definition-of-ref-assemblies, `ReferenceAssemblyAttribute` can be defined internally like other attributes.

Comment (jnm2) [reply TunnelVisionLabs.ReferenceAssemblyAnnotator/CustomAttributeFactory.cs:82]: I bet it's not necessary to define the `Description` property or constructor overload or to apply `[AttributeUsage]`.

Comment (jnm2) [reply TunnelVisionLabs.ReferenceAssemblyAnnotator/CustomAttributeFactory.cs:82]: Defining it would only be useful if you compile for net35 or earlier and the output assembly ends up getting used on net40 or later.

File: global.json (hunk 3 above)
Comment (sharwell) [reply global.json]: Can you file a bug to update the schema to include that property? 😸

Comment (jnm2) [reply global.json]: @sharwell I've never used VS to edit this file :D 

Looks like someone already did: https://github.com/dotnet/cli/issues/9341

Comment (jnm2) [reply global.json]: Hey, it's open-source, nice 
https://github.com/schemastore/schemastore/

File: TunnelVisionLabs.ReferenceAssemblyAnnotator/CustomAttributeFactory.cs (hunk 1 above)
Comment (sharwell) [reply TunnelVisionLabs.ReferenceAssemblyAnnotator/CustomAttributeFactory.cs:82]: ➡️ I updated the implementation to emit the attribute if it's not already available.

File: TunnelVisionLabs.ReferenceAssemblyAnnotator/Program.cs (hunk 2 above)
Comment (sharwell) [reply TunnelVisionLabs.ReferenceAssemblyAnnotator/Program.cs:111]: Fixed and also filed https://github.com/dotnet/roslyn/issues/38953

File: global.json (hunk 3 above)
Comment (sharwell) [reply global.json]: Fixed

File: TunnelVisionLabs.ReferenceAssemblyAnnotator/Program.cs [hunk 5]
```diff
@@ -281,6 +304,25 @@ private static TypeDefinition DefineEmbeddedAttribute(AssemblyDefinition assembl
...
 
+        private static TypeDefinition DefineReferenceAssemblyAttribute(AssemblyDefinition assemblyDefinition, (TypeReference systemAttribute, TypeReference systemRuntimeCompilerServicesCompilerGeneratedAttribute) wellKnownTypes)
+        {
+            var attribute = new TypeDefinition(
+                @namespace: "System.Runtime.CompilerServices",
+                name: "ReferenceAssemblyAttribute",
+                TypeAttributes.NotPublic | TypeAttributes.Sealed | TypeAttributes.BeforeFieldInit,
+                assemblyDefinition.MainModule.ImportReference(wellKnownTypes.systemAttribute));
+
+            var constructor = attribute.AddDefaultConstructor(assemblyDefinition.MainModule.TypeSystem);
```
Comment (jnm2) [inline TunnelVisionLabs.ReferenceAssemblyAnnotator/Program.cs]: Variable is unused.
